#!bash
#
# bash completion support for symfony2 console
#
# Copyright (C) 2010 Matthieu Bontemps <matthieu@knplabs.com>
# Distributed under the GNU General Public License, version 2.0.

_console() 
{
    # define our variables
    local cur prev opts cmd

    # blank COMPlete Reply variable
    COMPREPLY=()

    # set current word
    cur="${COMP_WORDS[COMP_CWORD]}"

    # set previous word
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    # set command as the first word app/console or similar
    cmd="${COMP_WORDS[0]}"

    # set options dynamically as generated by Symfony2 Command Component of our Bundle
    # this is probably NOT a good approach because it is dumping all options as a list
    opts=$(${cmd} console:autocomplete)

    # this does the first autocomplete for the first word after the app/console or
    # cmd command word
    #if [[ ${COMP_CWORD} = 1 ]] ; then
        COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
        return 0
    #fi

    # this does the second autocomplete for the second word after the first word
    # but only enters into effect when the previous word was help
    #if [[ ${COMP_CWORD} = 2 ]] ; then
    #    case "${prev}" in
    #        help)
    #            COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
    #            return 0
    #            ;;
    #        *)
    #            ;;
    #    esac
    #fi

    # this does the autocomplete for the following words
    # but only addresses case when the word being completed starts with --
    #if [[ ${COMP_CWORD} > 1 ]] ; then
    #    case "${cur}" in
    #        --*)
    #            COMPREPLY=( $(compgen -W "$(${cmd} console:autocomplete ${COMP_WORDS[1]})" -- ${cur}) )
    #            return 0
    #            ;;
    #        *)
    #            ;;
    #    esac
    #fi

    # if all fails to return finally completes for a [filename] current word
    #COMPREPLY=( $(compgen -f ${cur}) )
    #return 0
}
# completes with this closure the command console
complete -F _console console
# completes with this closure the command Symfony
complete -F _console Symfony
# set the character for separation besides spaces we have :
COMP_WORDBREAKS=${COMP_WORDBREAKS//:}